name: Merge to Release

on:
  push:
    branches:
      - develop

jobs:
  merge-to-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Git
      run: |
        git config user.name "${{ secrets.GITHUB_ACTOR }}"
        git config user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"

    - name: Create PR to Release
      run: |
        git checkout -b merge-to-release
        git merge --no-ff develop
        git push origin merge-to-release

    - name: Open Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Merge develop into release"
        title: "Merge develop into release"
        branch: merge-to-release
